version: '3'
services:
  odfe-node1:
    restart: always
    image: amazon/opendistro-for-elasticsearch:0.7.1
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        #- network.host=0.0.0.0 # required if not using the demo Security configuration
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./esnode-1.pem:/usr/share/elasticsearch/config/esnode.pem
      - ./esnode-1-key.pem:/usr/share/elasticsearch/config/esnode-key.pem
      - ./kirk.pem:/usr/share/elasticsearch/config/kirk.pem
      - ./kirk-key.pem:/usr/share/elasticsearch/config/kirk-key.pem
      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
        #  odfe-node2:
        #    restart: always
        #    image: amazon/opendistro-for-elasticsearch:0.7.1
        #    container_name: odfe-node2
        #    environment:
        #      - cluster.name=odfe-cluster
        #      - bootstrap.memory_lock=true
        #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        #      - discovery.zen.ping.unicast.hosts=odfe-node1
        #      - network.host=0.0.0.0
        #    ulimits:
        #      memlock:
        #        soft: -1
        #        hard: -1
        #    volumes:
        #      - odfe-data2:/usr/share/elasticsearch/data
        #      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
        #      - ./esnode-2.pem:/usr/share/elasticsearch/config/esnode.pem
        #      - ./esnode-2-key.pem:/usr/share/elasticsearch/config/esnode-key.pem
        #      - ./kirk.pem:/usr/share/elasticsearch/config/kirk.pem
        #      - ./kirk-key.pem:/usr/share/elasticsearch/config/kirk-key.pem
        #      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        #      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
        #    networks:
        #      - odfe-net
  kibana:
    restart: always
    image: amazon/opendistro-for-elasticsearch-kibana:0.7.1
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: /usr/share/kibana/config/kibana-key.pem
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/kibana.pem
    volumes:
      - ./root-ca.pem:/usr/share/kibana/config/root-ca.pem
      - ./kibana.pem:/usr/share/kibana/config/kibana.pem
      - ./kibana-key.pem:/usr/share/kibana/config/kibana-key.pem
      - ./custom-kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
